# must have space after every colon (:) to make sure it works
server:
 port: 8001

mybatis:
 config-location: classpath:mybatis/mybatis.cfg.xml
 type-aliases-package: pers.xiaoming.springcloud.entity
 mapper-locations:
 - classpath:mybatis/mapper/**/*.xml

# before 'type', 'driver-class-name', there shouldn't be any tab, only one space make it work
spring:
  application:
   name: springcloud-webservice
  datasource:
   type: com.zaxxer.hikari.HikariDataSource
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql:///spring?useSSL=true
   username: root
   password: root
   hikari:
    minimum-dile: 2
    maximum-pool-size: 10
    pool-name: springcloud-mysql-connetction-pool
    idle-timeout: 500
    connection-timeout: 1000
    max-lifetime: 600000

eureka:
  client: #Register to eureka service list
   service-url:
     defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: springcloud-webservice-8001
    prefer-ip-address: true

info:
  app.name: xiaoming-springcloud-webservice
  build.artifactId: $project.artifactId$
  build.version: $project.version$